### PR TITLE
Add Browserify / CommonJS support (dev branch rebased)

### PR DESCRIPTION
**Pull request by Klowner**
Rebased the excellent work by @wookiehangover from https://github.com/adobe-webplatform/Snap.svg/pull/170

### CODE REVIEW

**Comment by alexanderatallah** [comment]
When will this be merged into master?

**Comment by wookiehangover** [comment]
lol'ing at how long ago this was "done" and could have been merged. Really gang, a year and a half for a 3 commit common js patch?

**Comment by andrew-minted** [comment]
+1. This needs to be merged ASAP.

**Comment by Klowner** [comment]
+1 :dancers:

**Comment by brianfeister** [comment]
+1 :+1: Please merge! :dancers::dancers::dancers:

**Comment by wookiehangover** [comment]
There have been [3 total](http://eclipse.gsfc.nasa.gov/OH/OH2014.html#LE2014Apr15T) [lunar](http://eclipse.gsfc.nasa.gov/OH/OH2014.html#LE2014Oct08T) [eclipses](http://eclipse.gsfc.nasa.gov/LEplot/LEplot2001/LE2015Apr04T.pdf) since the work for this was originally completed (Jan 2014)

**Comment by brianfeister** [comment]
Lol. wait, what?! I thought I must be crazy.  Do we still not have non-AMD support for this?

**Comment by DmitryBaranovskiy** [comment]
@wookiehangover @brianfeister It is in `master`: https://github.com/adobe-webplatform/Snap.svg/commits/master/src/svg.js

**Pull request merged**
